---
- name: Teardown environment
  hosts: testmachines
  tags:
      - teardown
      - teardownenv
  roles:
      - environment/teardown

- name: Install libvirt packages and configure networks
  hosts: testmachines 
  gather_facts: yes
  tags:
      - setup
  roles:
      - environment/setup

- name: Teardown virtual machines
  hosts: testmachines
  gather_facts: yes
  tags:
      - teardown
      - teardownvms
  roles:
      - libvirt/teardown

- name: Start virtual machines from images
  hosts: testmachines
  gather_facts: yes
  tags:
      - setup
      - createvms
  roles:
      - libvirt/setup

- name: Install filebeat on all machines
  hosts: all
  become: yes
  gather_facts: yes
  tags:
      - setup
      - provisionfb
  roles:
    -  ansible-role-filebeat

- name: Install elasticsearch, logstash and kibana on localhost
  hosts: localhost
  become: yes
  gather_facts: yes
  tags:
      - setup
      - provisionelk
  roles:
    - ansible-role-elasticsearch
    - ansible-role-logstash

- name: Provision sipp servers
  gather_facts: yes
  hosts: sipp_server
  tags:
    - setup
    - createvms
    - provisionsipp
  roles:
    - sipp/setup/server

- name: Provision Asterisk proxy
  gather_facts: yes
  hosts: asterisk
  tags:
    - provisionast
    - createvms
    - setup
  roles:
    - asterisk/setup

- name: Provision sipp clients
  gather_facts: yes
  hosts: sipp_client
  tags:
    - setup
    - createvms
    - provisionsipp
  roles:
    - sipp/setup/client

- name: Kill SIPP on server and clients
  hosts: sipp_client,sipp_server
  tags:
    - teardown
    - teardownvms
    - teardownsipp
  roles:
    - sipp/teardown

